Application has thrown an uncaught exception and is terminated:
Error: failed to connect to [192.168.88.128:27017]
    at null.<anonymous> (D:\Projects\Kaveh\KIG\TCS_Services\tcs_services\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:540:74)
    at emit (events.js:106:17)
    at null.<anonymous> (D:\Projects\Kaveh\KIG\TCS_Services\tcs_services\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (D:\Projects\Kaveh\KIG\TCS_Services\tcs_services\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:478:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
